ShoppingCart/Models/Author.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShoppingCart.Models
{
    public class Author
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        
    }
}

ShoppingCart/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShoppingCart.Models
{
    public class Book
    {
        public int Id { get; set; }
        public string Isbn { get; set; }
        public string Title { get; set; }
        public int ReleaseYear { get; set; }
        public string Category { get; set; }
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }
        public string Author { get; set; }

    }
}

ShoppingCart/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShoppingCart.Models
{
    public class Category
    {
        public int CategoryId { get; set; }
        public string Description { get; set; }
    }
}

ShoppingCart/Models/ErrorViewModel.cs
using System;

namespace ShoppingCart.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ShoppingCart/Models/ShoppingCartItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShoppingCart.Models
{
    public class ShoppingCartItem
    {

        public int ShoppingCartItemId { get; set; }
                
        public Book Book { get; set; }

        public decimal UnitPrice { get; set; }

        public string ShoppingCartId { get; set; }
    }
}

ShoppingCart/ViewModels/BooksByAuthorVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ShoppingCart.Models;

namespace ShoppingCart.ViewModels
{
    public class BooksByAuthorVM
    {
        public IEnumerable<Book> Books { get; set; }

        public string AuthorName { get; set; }
    }
}

ShoppingCart/ViewModels/BooksByCategoryVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ShoppingCart.Models;

namespace ShoppingCart.ViewModels
{
    public class BooksByCategoryVM
    {
        public IEnumerable<Book> Books { get; set; }

        public string Category { get; set; }
    }
}

ShoppingCart/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ShoppingCart.Models;
using ShoppingCart.Repositories;

namespace ShoppingCart.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IAuthorRepository _authorRepo;

        public AuthorController(IAuthorRepository authorRepo)
        {
            _authorRepo = authorRepo;
        }

        public ViewResult AllAuthors()
        {
            return View(_authorRepo.AllAuthors);
        }
    }
}

ShoppingCart/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ShoppingCart.Models;
using ShoppingCart.Repositories;
using ShoppingCart.ViewModels;

namespace ShoppingCart.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository _bookRepo;
        private readonly ICategoryRepository _categoryRepo;
        private readonly IAuthorRepository _authorRepo;

        public BookController(IBookRepository bookRepo, ICategoryRepository categoryRepo, IAuthorRepository authorRepo)
        {
            _bookRepo = bookRepo;
            _categoryRepo = categoryRepo;
            _authorRepo = authorRepo;
        }

        public ViewResult Catalog()
        {
            return View(_bookRepo.AllBooks);
        }

        public ViewResult OnSale()
        {
            return View(_bookRepo.OnSale);
        }

        public IActionResult Details(int id)
        {
            var book = _bookRepo.GetBookById(id);

            return View(book);
        }

        public ViewResult ByAuthor(string name)
        {
            return View(new BooksByAuthorVM
            {
                Books = _bookRepo.GetBooksOfAuthor(name),
                AuthorName = name
            });
        }

        #region CodeToBeDisposed
        //public ViewResult ByCategory()
        //{
        //    List<Book> Books = _bookRepo.AllBooks.ToList();

        //    BookListVM bookListVM = new()
        //    {
        //        Books = _bookRepo.AllBooks.Where(c=>c.Category == _categoryRepo.GetCategoryById(1).Description),
        //        SelectedCategoryDescription= _categoryRepo.GetCategoryById(2).Description
        //    };

        //    return View(bookListVM);
        //}

        //public void BookPurchased(int id)
        //{
        //    Book PurchasedBook = _bookRepo.GetBookById(id);
        //    int Quantity = 1; //TODO: Get the value from user

        //    CartItem Item = new CartItem();
        //    Item.PurchasedBook = PurchasedBook;
        //    Item.Quantity = Quantity;

        //    var result = _shoppingCartRepository.AddItem(Item);

        //}
        #endregion

    }
}

ShoppingCart/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ShoppingCart.Models;
using ShoppingCart.Repositories;

namespace ShoppingCart.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepo;
       
        public CategoryController(ICategoryRepository categoryRepo)
        {
            _categoryRepo = categoryRepo;
        }

        public ViewResult AllCategories()
        {
            return View(_categoryRepo.AllCategories);
        }
    }
}

ShoppingCart/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ShoppingCart.Repositories;
using ShoppingCart.Models;

namespace ShoppingCart.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IBookRepository _bookRepo;
        private readonly EFShoppingCartRepository _cartRepo;

        public ShoppingCartController(IBookRepository bookRepo, EFShoppingCartRepository cartRepo)
        {
            _bookRepo = bookRepo;
            _cartRepo = cartRepo;

        }

        public IActionResult Index()
        {
            _cartRepo.ShoppingCartItems = _cartRepo.GetShoppingCartItems();

            return View(_cartRepo);
        }

        public RedirectToActionResult AddToShoppingCart(int Id)
        {
            var selectedBook = _bookRepo.GetBookById(Id);

            if (selectedBook != null)
            {
                _cartRepo.AddItem(selectedBook);
            }

            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int Id)
        {
            var selectedBook = _bookRepo.GetBookById(Id);

            if (selectedBook != null)
            {
                _cartRepo.RemoveItem(selectedBook);
            }

            return RedirectToAction("Index");
        }
    }
}

ShoppingCart/Views/Author/AllAuthors.cshtml
@model IEnumerable<ShoppingCart.Models.Author>
    <div class="jumbotron">
        <h2>List of All Authors </h2>
    </div>
        <table class="col-12 table-bordered">
            <thead class="text-center">
                <tr>
                    <th class="col-1" scope="col">#</th>
                    <th class="col-6" scope="col">Name</th>
                    <th class="col-2" scope="col">View Collection</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var author in Model)
                {
                    <tr>
                        <th class="text-center">@author.Id</th>
                        <td class="text-center">@author.FirstName @author.LastName</td>
                        <td class="text-center"><a asp-action="ByAuthor" asp-controller="Book" asp-route-name="@author.FirstName @author.LastName" class="btn btn-primary">View</a></td>
                    </tr>
                }
            </tbody>
        </table>

ShoppingCart/Views/Book/ByAuthor.cshtml
@model ShoppingCart.ViewModels.BooksByAuthorVM

    <div class="jumbotron">
        <h2 class="text-center">All Books of @Model.AuthorName</h2>
    </div>
<div class="container">
    <div class="row">
        @foreach (var book in Model.Books)
        {
            <div class="col-4 mb-4">
                <div class="card">
                    <img class="card-img-top" style="max-height:25em" src="/img/@book.ImageUrl" alt="bookthumbnail" />
                    <div class="card-body d-flex flex-column h-100">
                        <h4 class="card-title">@book.Title</h4>
                        <p class="card-text">@book.Author</p>
                        <p class="card-text font-weight-bold">CAD$ @book.Price</p>
                        <div class="align-content-center align-items-center">
                            <a asp-action="Details" asp-controller="Book" asp-route-id="@book.Id" class="btn btn-primary text-white">More Details</a>
                            <a asp-action="AddToShoppingCart" asp-controller="ShoppingCart" asp-route-Id="@book.Id" class="btn btn-primary">Buy It</a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

ShoppingCart/Views/Book/Catalog.cshtml
@model IEnumerable<ShoppingCart.Models.Book>

@{
    ViewData["Title"] = "Books";
}

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Welcome to Book Store</title>
</head>
<body>
    <div class="container">
        <div class="row">
            @foreach (var book in Model)
            {
                <div class="col-4 mb-4">
                    <div class="card">
                        <img class="card-img-top" style="max-height:25em" src="./img/@book.ImageUrl" alt="bookthumbnail" />
                        <div class="card-body d-flex flex-column h-100">
                            <h4 class="card-title">@book.Title</h4>
                            <p class="card-text">@book.Author</p>
                            <p class="card-text font-weight-bold">CAD$ @book.Price</p>
                            <div class="align-content-center align-items-center">
                                <a asp-action="Details" asp-controller="Book" asp-route-id="@book.Id" class="btn btn-primary text-white">More Details</a>
                                <a asp-action="AddToShoppingCart" asp-controller="ShoppingCart" asp-route-Id="@book.Id" class="btn btn-primary">Buy It</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

</body>
</html>

ShoppingCart/Views/Book/Details.cshtml
@model Book


<div class="card mb-3">
    <div class="row no-gutters">
        <div class="col-md-4">
            <img style="max-width:375px" src="/img/@Model.ImageUrl" alt="bookthumbnail">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">@Model.Title</h5>
                <h6 class="card-title">@Model.Author</h6>
                <h6 class="card-title">@Model.Category</h6>
                <p class="card-text">Description : is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum </p>
                <p class="card-text">CAD$ @Model.Price</p>
                <a asp-route-id="@Model.Id" asp-action="AddToShoppingCart" asp-controller="ShoppingCart" class="btn btn-primary">Buy It</a>
            </div>
        </div>
    </div>
</div>

ShoppingCart/Views/Book/OnSale.cshtml
@model IEnumerable<ShoppingCart.Models.Book>

@{
    ViewData["Title"] = "Books";
}

<div class="jumbotron">
    <h2 class="text-center">Grab Your Discounts Now!! Don't Be Late!!</h2>
</div>

    <div class="container">
        <div class="row">
            @foreach (var book in Model)
            {
                <div class="col-4 mb-4">
                    <div class="card">
                        <h4 class="card-header text-center">@book.Title</h4>
                        <div class="card-body d-flex flex-column h-100">
                            <p class="card-text">@book.Author</p>
                            <p class="card-text font-weight-bold">CAD$ @book.Price</p>
                            <div class="align-content-center align-items-center">
                                <a asp-route-id="@book.Id" asp-action="AddToShoppingCart" asp-controller="ShoppingCart" class="btn btn-primary">Buy It</a>
                                <a asp-route-id="@book.Id" asp-action="Details" asp-controller="Book" class="btn btn-primary">More Details</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

ShoppingCart/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BookLust Online BookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Book" asp-action="Catalog">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Catalog">All Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="AllCategories">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="AllAuthors">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="OnSale">On Sale</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BookLust Book Store - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ShoppingCart/Views/ShoppingCart/Index.cshtml
@model EFShoppingCartRepository
    
<h2>Shopping Cart</h2>
<hr />
<table class="table table-bordered">
    <tr>
        <th>Book Title</th>
        <th class="text-right">Unit Price</th>
        <th class="text-center"><p>Remove (X)</p></th>
    </tr>

    @foreach (var cartItem in Model.ShoppingCartItems)
    {
<tr>
    <td class="text-left">@cartItem.Book.Title</td>
    <td class="text-right">@cartItem.Book.Price</td>
    <td class="text-center"><a asp-route-id="@cartItem.Book.Id" asp-action="RemoveFromShoppingCart" asp-controller="ShoppingCart" class="btn btn-warning">Remove</a></td>
</tr>
    }

<tr>
    <th><b>Total</b></th>
    <th class="text-right"><b>@Model.GetShoppingCartTotal()</b></th>
</tr>
</table>
<hr />
<div>
    <a asp-action="Catalog" asp-controller="Book" class="btn btn-primary">Back To Catalog</a>
</div>